### ISSUE TITLE
"Cannot find module 'core-js/modules/web.dom.iterable'"

### ISSUE THREAD

**Issue by rtgrrk** [janumedia/vue-storybook-example#4]
an error appears after install i + npm run storybook:serve

"Cannot find module 'core-js/modules/web.dom.iterable'"

probably a babel issue. uncommenting the preset helps

. module.exports = {
  // presets: ["@vue/app"],
};

**Comment by janumedia** [comment]
> an error appears after install i + npm run storybook:serve
> 
> "Cannot find module 'core-js/modules/web.dom.iterable'"
> 
> probably a babel issue. uncommenting the preset helps
> 
> . module.exports = {
> // presets: ["@vue/app"],
> };

Which Storybook version do you use? There was some issue related to core-js 3 and later [in this thead](https://github.com/storybookjs/storybook/issues/6204#issue-423435302)

Also in my example is Storybook 4 and as far as I know only work with core-js 2

**Comment by rtgrrk** [comment]
could be my bad. I was uninstall installing a lot to get this working

The storybook version is 6.14.5 and js-core is on version 3.6.5. just uncommenting presets in babel.config.js worked in my case

$ cat package.json
{
  "name": "storybook-test-project",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "storybook:serve": "vue-cli-service storybook:serve -p 6006 -c config/storybook",
    "storybook:build": "vue-cli-service storybook:build -c config/storybook"
  },
  "dependencies": {
    "@babel/runtime-corejs3": "^7.11.0",
    "babel-loader": "^8.1.0",
    "core-js": "^3.6.5",
    "vue": "^2.6.6"
  },
  "devDependencies": {
    "@storybook/addon-actions": "^4.1.0 || ^5.0.0",
    "@storybook/addon-knobs": "^4.1.0 || ^5.0.0",
    "@storybook/addon-links": "^4.1.0 || ^5.0.0",
    "@storybook/addon-notes": "^4.1.0 || ^5.0.0",
    "@vue/cli-plugin-babel": "^3.0.0",
    "@vue/cli-plugin-eslint": "^3.0.0",
    "@vue/cli-service": "^3.0.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.8.0",
    "eslint-plugin-vue": "^5.0.0",
    "vue-cli-plugin-storybook": "^0.6.1",
    "vue-template-compiler": "^2.5.21",
    "vue-storybook": "^1.0.0-1"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  }
}

**Comment by rtgrrk** [comment]
storybook version is probably 5.3.19 btw

npm -v storybook
says 6.14.5

npm run storybook:serve
says Storybook 5.3.19 started

**Comment by janumedia** [comment]
> could be my bad. I was uninstall installing a lot to get this working
> 
> The storybook version is 6.14.5 and js-core is on version 3.6.5. just uncommenting presets in babel.config.js worked in my case
> 
> $ cat package.json
> {
> "name": "storybook-test-project",
> "version": "0.1.0",
> "private": true,
> "scripts": {
> "serve": "vue-cli-service serve",
> "build": "vue-cli-service build",
> "lint": "vue-cli-service lint",
> "storybook:serve": "vue-cli-service storybook:serve -p 6006 -c config/storybook",
> "storybook:build": "vue-cli-service storybook:build -c config/storybook"
> },
> "dependencies": {
> "@babel/runtime-corejs3": "^7.11.0",
> "babel-loader": "^8.1.0",
> "core-js": "^3.6.5",
> "vue": "^2.6.6"
> },
> "devDependencies": {
> "@storybook/addon-actions": "^4.1.0 || ^5.0.0",
> "@storybook/addon-knobs": "^4.1.0 || ^5.0.0",
> "@storybook/addon-links": "^4.1.0 || ^5.0.0",
> "@storybook/addon-notes": "^4.1.0 || ^5.0.0",
> "@vue/cli-plugin-babel": "^3.0.0",
> "@vue/cli-plugin-eslint": "^3.0.0",
> "@vue/cli-service": "^3.0.0",
> "babel-eslint": "^10.0.1",
> "eslint": "^5.8.0",
> "eslint-plugin-vue": "^5.0.0",
> "vue-cli-plugin-storybook": "^0.6.1",
> "vue-template-compiler": "^2.5.21",
> "vue-storybook": "^1.0.0-1"
> },
> "eslintConfig": {
> "root": true,
> "env": {
> "node": true
> },
> "extends": [
> "plugin:vue/essential",
> "eslint:recommended"
> ],
> "rules": {},
> "parserOptions": {
> "parser": "babel-eslint"
> }
> },
> "postcss": {
> "plugins": {
> "autoprefixer": {}
> }
> }
> }

Ah ic, you're using  `vue-storybook` with `vue-cli-plugin-storybook`, and not `@storybook/vue`.
My example following official Storybook js [guide for vue](https://storybook.js.org/docs/guides/guide-vue/). Less pain (to me). And  I personally prefer using `@storybook/vue` and not to include `<story>` tag inside your component. Because that outside component jobs and keep your component clean.
